# Generated by Django 4.2.1 on 2023-05-17 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coachs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingrese el nombre del coach del equipo', max_length=200)),
                ('photo', models.ImageField(default=None, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='equipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingrese el nombre del equipo', max_length=200, verbose_name='Nombre')),
                ('photo', models.ImageField(default=None, upload_to='images/')),
                ('coach_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appteams.coachs')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['liga_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('foto', models.ImageField(default=None, upload_to='images/')),
                ('cant_teams', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('status_play', models.CharField(choices=[('cre', 'Creado'), ('prog', 'Programado'), ('rea', 'Realizado'), ('can', 'Cancelado')], default='cre', max_length=4)),
                ('liga', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appteams.league')),
            ],
        ),
        migrations.CreateModel(
            name='poblaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Play_Arbitro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.CharField(choices=[('cen', 'Central'), ('ban', 'Bandera'), ('otro', 'Otro')], default='cen', max_length=4)),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appteams.play')),
            ],
        ),
        migrations.CreateModel(
            name='jugadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingrese el nombre del jugador', max_length=200)),
                ('photo', models.ImageField(default=None, upload_to='images/')),
                ('numero', models.IntegerField(help_text='Numero de playera', verbose_name='Numero')),
                ('posicion', models.CharField(choices=[('del', 'Delantero'), ('def', 'Defensa'), ('por', 'Portero'), ('car', 'Carrilero'), ('cen', 'Central')], default='del', max_length=3)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores_ids', to='appteams.equipos')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'ordering': ['team', 'name'],
            },
        ),
        migrations.CreateModel(
            name='estadios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingrese el nombre del estadio', max_length=200)),
                ('photo', models.ImageField(default=None, upload_to='images/')),
                ('liga_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appteams.league')),
            ],
            options={
                'verbose_name': 'Estadio',
                'verbose_name_plural': 'Estadios',
                'ordering': ['liga_id', 'name'],
            },
        ),
        migrations.AddField(
            model_name='equipos',
            name='liga_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appteams.league'),
        ),
        migrations.CreateModel(
            name='cedulas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Titulo')),
                ('play_desc', models.CharField(max_length=200)),
                ('resultado', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('state', models.CharField(choices=[('cre', 'Creado'), ('env', 'Enviada'), ('can', 'Cancelado')], default='cre', max_length=3)),
                ('play_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appteams.play', verbose_name='Juego')),
                ('playera_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appteams.jugadores')),
            ],
        ),
        migrations.CreateModel(
            name='arbitros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingrese el nombre del arbitro', max_length=200)),
                ('photo', models.ImageField(default=None, upload_to='images/')),
                ('liga_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appteams.league')),
            ],
            options={
                'verbose_name': 'Arbitro',
                'verbose_name_plural': 'Arbitros',
                'ordering': ['liga_id', 'name'],
            },
        ),
    ]
