# Generated by Django 4.2.1 on 2023-05-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appteams', '0002_alter_league_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cedulas',
            name='fecha_inicio',
            field=models.DateTimeField(),
        ),
    ]
