# Generated by Django 4.2.1 on 2023-05-18 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appteams', '0004_alter_play_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cedulas',
            name='state',
        ),
        migrations.AlterField(
            model_name='arbitros',
            name='liga_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appteams.league', verbose_name='Nombre de la liga'),
        ),
        migrations.AlterField(
            model_name='arbitros',
            name='name',
            field=models.CharField(help_text='Nombre del arbitro', max_length=200),
        ),
        migrations.AlterField(
            model_name='arbitros',
            name='photo',
            field=models.ImageField(default=None, upload_to='images/', verbose_name='Foto del arbitro'),
        ),
        migrations.AlterField(
            model_name='cedulas',
            name='fecha_fin',
            field=models.DateField(verbose_name='Fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='cedulas',
            name='fecha_inicio',
            field=models.DateTimeField(verbose_name='Fecha de incio'),
        ),
        migrations.AlterField(
            model_name='cedulas',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Folio'),
        ),
        migrations.AlterField(
            model_name='cedulas',
            name='play_desc',
            field=models.CharField(max_length=200, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='cedulas',
            name='playera_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appteams.jugadores', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='cedulas',
            name='resultado',
            field=models.CharField(max_length=200, verbose_name='Resultado del partido'),
        ),
        migrations.AlterField(
            model_name='coachs',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre del coach'),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre del equipo'),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='photo',
            field=models.ImageField(default=None, upload_to='images/', verbose_name='Foto del equipo'),
        ),
        migrations.AlterField(
            model_name='estadios',
            name='liga_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appteams.league', verbose_name='Liga'),
        ),
        migrations.AlterField(
            model_name='estadios',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre del estadio'),
        ),
        migrations.AlterField(
            model_name='estadios',
            name='photo',
            field=models.ImageField(default=None, upload_to='images/', verbose_name='Foto del estadio'),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre del jugador'),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='numero',
            field=models.IntegerField(verbose_name='Número de la playera'),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='photo',
            field=models.ImageField(default=None, upload_to='images/', verbose_name='Foto del jugador'),
        ),
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre de la liga'),
        ),
        migrations.AlterField(
            model_name='play',
            name='folio',
            field=models.CharField(max_length=200, verbose_name='Folio'),
        ),
    ]
