# Generated by Django 4.2.1 on 2023-05-19 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appteams', '0006_alter_arbitros_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cedulas',
            name='playera_id',
        ),
    ]
