# Generated by Django 4.2.1 on 2023-05-19 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appteams', '0007_remove_cedulas_playera_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='cant_teams',
        ),
        migrations.AlterField(
            model_name='arbitros',
            name='liga_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appteams.league', verbose_name='Liga'),
        ),
        migrations.AlterField(
            model_name='arbitros',
            name='photo',
            field=models.ImageField(default=None, upload_to='images/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='coachs',
            name='photo',
            field=models.ImageField(default=None, upload_to='images/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='coach_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appteams.coachs', verbose_name='Coach'),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='liga_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appteams.league', verbose_name='Liga'),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='photo',
            field=models.ImageField(default=None, upload_to='images/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='photo',
            field=models.ImageField(default=None, upload_to='images/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='posicion',
            field=models.CharField(choices=[('del', 'Delantero'), ('def', 'Defensa'), ('por', 'Portero'), ('car', 'Carrilero'), ('cen', 'Central')], default='del', max_length=3, verbose_name='Posición'),
        ),
        migrations.AlterField(
            model_name='jugadores',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores_ids', to='appteams.equipos', verbose_name='Equipo'),
        ),
        migrations.AlterField(
            model_name='league',
            name='foto',
            field=models.ImageField(upload_to='images/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='play',
            name='liga',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appteams.league', verbose_name='Liga'),
        ),
    ]
