# Generated by Django 4.2.1 on 2023-05-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appteams', '0008_remove_league_cant_teams_alter_arbitros_liga_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='jugadores2_ids',
            field=models.ManyToManyField(to='appteams.jugadores', verbose_name='Jugadores'),
        ),
    ]
