# Generated by Django 4.2.1 on 2023-05-20 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appteams', '0009_equipos_jugadores2_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipos',
            name='jugadores2_ids',
        ),
    ]
