# Generated by Django 4.2.1 on 2023-05-20 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appteams', '0010_remove_equipos_jugadores2_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play',
            name='status_play',
        ),
        migrations.AddField(
            model_name='play',
            name='arbitro',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appteams.arbitros', verbose_name='Arbitro'),
        ),
        migrations.AddField(
            model_name='play',
            name='estadio',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appteams.estadios', verbose_name='Estadio'),
        ),
        migrations.AddField(
            model_name='play',
            name='posicion',
            field=models.CharField(choices=[('cen', 'Central'), ('ban', 'Bandera'), ('otro', 'Otro')], default='cen', max_length=4, verbose_name='Posición del arbitro'),
        ),
        migrations.AddField(
            model_name='play',
            name='team1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='team1_plays', to='appteams.equipos', verbose_name='Equipo Local'),
        ),
        migrations.AddField(
            model_name='play',
            name='team2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='team2_plays', to='appteams.equipos', verbose_name='Equipo Visitante'),
        ),
        migrations.AlterField(
            model_name='arbitros',
            name='photo',
            field=models.ImageField(upload_to='images/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='estadios',
            name='photo',
            field=models.ImageField(upload_to='images/', verbose_name='Foto del estadio'),
        ),
        migrations.AlterField(
            model_name='play',
            name='liga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appteams.league', verbose_name='Liga'),
        ),
        migrations.DeleteModel(
            name='Play_Arbitro',
        ),
    ]
