# Generated by Django 4.2.1 on 2023-05-27 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appteams', '0011_remove_play_status_play_play_arbitro_play_estadio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='arbitro_1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='primer_arbitro', to='appteams.arbitros', verbose_name='Primer Arbitro'),
        ),
        migrations.AlterField(
            model_name='play',
            name='posicion',
            field=models.CharField(choices=[('cen', 'Central'), ('ban', 'Bandera'), ('otro', 'Otro')], default='cen', max_length=4, verbose_name='Posición del primer arbitro'),
        ),
    ]
