# Generated by Django 4.2.1 on 2023-05-27 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appteams', '0012_play_arbitro_1_alter_play_posicion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play',
            name='arbitro',
        ),
        migrations.AlterField(
            model_name='play',
            name='arbitro_1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appteams.arbitros', verbose_name='Arbitro'),
        ),
    ]
