# Generated by Django 4.2.1 on 2023-05-27 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appteams', '0013_remove_play_arbitro_alter_play_arbitro_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='play',
            old_name='posicion',
            new_name='posicion_arbitro_1',
        ),
        migrations.AddField(
            model_name='play',
            name='arbitro_2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='segundo_arbitro', to='appteams.arbitros', verbose_name='Segundo Arbitro'),
        ),
        migrations.AddField(
            model_name='play',
            name='arbitro_3',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tercer_arbitro', to='appteams.arbitros', verbose_name='Tercer Arbitro'),
        ),
        migrations.AddField(
            model_name='play',
            name='arbitro_4',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cuarto_arbitro', to='appteams.arbitros', verbose_name='Cuarto Arbitro'),
        ),
        migrations.AddField(
            model_name='play',
            name='posicion_arbitro_2',
            field=models.CharField(choices=[('cen', 'Central'), ('ban', 'Bandera'), ('otro', 'Otro')], default='cen', max_length=4, verbose_name='Posición del segundo arbitro'),
        ),
        migrations.AddField(
            model_name='play',
            name='posicion_arbitro_3',
            field=models.CharField(choices=[('cen', 'Central'), ('ban', 'Bandera'), ('otro', 'Otro')], default='cen', max_length=4, verbose_name='Posición del tercer arbitro'),
        ),
        migrations.AddField(
            model_name='play',
            name='posicion_arbitro_4',
            field=models.CharField(choices=[('cen', 'Central'), ('ban', 'Bandera'), ('otro', 'Otro')], default='cen', max_length=4, verbose_name='Posición del cuarto arbitro'),
        ),
        migrations.AlterField(
            model_name='play',
            name='arbitro_1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='primer_arbitro', to='appteams.arbitros', verbose_name='Primer Arbitro'),
        ),
    ]
