# Generated by Django 4.2.1 on 2023-05-29 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appteams', '0015_alter_equipos_coach_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='estadio',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appteams.estadios', verbose_name='Estadio'),
        ),
        migrations.AlterField(
            model_name='play',
            name='team1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team1_plays', to='appteams.equipos', verbose_name='Equipo Local'),
        ),
        migrations.AlterField(
            model_name='play',
            name='team2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team2_plays', to='appteams.equipos', verbose_name='Equipo Visitante'),
        ),
    ]
