# Generated by Django 4.2.1 on 2023-05-29 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appteams', '0016_alter_play_estadio_alter_play_team1_alter_play_team2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='liga_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appteams.league', verbose_name='Liga'),
        ),
    ]
